### ISSUE TITLE
声卡？

### ISSUE THREAD

**Issue by Zyjacya-In-love** [meikeeit/Hackintosh_Dell3543#1]
我和你的电脑型号相同，但是我在安装各种声卡驱动，但是内置扬声器依旧没有声音（耳机有声音），请问你的电脑有声音吗？

**Comment by meikeeit** [comment]
声卡就是applealc+layout id，好像DSDT我有加几个相关的Rehabman的FIX。你如果用过voodoohda就只能重装。这个只需要选择inject kexts启动就可以了，不需要动系统文件，安装后要不要把kexts复制进系统就随意了

**Comment by meikeeit** [comment]
我把这几个FIX做进DSDT了，你可以删掉DSDT然后在clover configure里选上，应该也可以，或者重做DSDT

			<key>Fixes</key>
			<dict>
				<key>Comment-IRQ Fix</key>
				<string>The following fixes may be needed for onboard audio/USB/etc</string>
				<key>FixTMR</key>
				<false/>
				<key>FixRTC</key>
				<false/>
				<key>FixIPIC</key>
				<false/>
				<key>FixHPET</key>
				<false/>
                       </dict>

**Comment by Zyjacya-In-love** [comment]
谢谢，我已经解决了这个问题
